BlogApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name='Blog'),
    path('category/<int:category_id>/', views.category, name='Category'),
]

CartApp/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('add/<int:product_id>/', views.add_product, name='Add'),
    path('delete/<int:product_id>/', views.delete_product, name='Delete'),
    path('rest/<int:product_id>/', views.rest_product, name='Rest'),
    path('empty/', views.empty_car, name='Empty'),
]

Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('OnlineStoreApp.urls')),
    path('services/', include('ServicesApp.urls')),
    path('blog/', include('BlogApp.urls')),
    path('contact/', include('ContactApp.urls')),
    path('store/', include('StoreApp.urls')),
    path('cart/', include('CartApp.urls')),
    path('admon/', include('AdminApp.urls')),
    path('accounts/', include('AccountsApp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

StoreApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='Store'),
    path('cart', views.cart, name='Cart'),
]

StoreApp/models.py
from django.db import models

# Create your models here.


class CategoryProd(models.Model):
    name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "categoryProd"
        verbose_name_plural = "categoriesProd"


class Product(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(CategoryProd, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="StoreApp")
    description = models.CharField(max_length=300)
    platform = models.CharField(max_length=50)
    classification = models.CharField(max_length=20)
    price = models.FloatField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "product"
        verbose_name_plural = "products"

StoreApp/views.py
from django.db.models import Q
from django.shortcuts import render
from .models import Product, CategoryProd
from django.core.paginator import Paginator # import Paginator

# Create your views here.


def store(request):
    products = Product.objects.all()
    paginator = Paginator(products, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    searched = request.POST.get('search')
    if searched:
        users = Product.objects.filter(
            Q(username__icontains=searched) |
            Q(first_name__icontains=searched) |
            Q(last_name__icontains=searched) |
            Q(email__icontains=searched)
        ).distinct()

    return render(request, "store/store.html", {'products': page_obj})


def cart(request):

    return render(request, "store/cart.html")

StoreApp/templates/store/cart.html
{% extends "OnlineStoreApp/base.html" %}

{% load static %}

{% block head %}

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Online Store</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'OnlineStoreApp/assets/base.ico' %}"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'OnlineStoreApp/css/styles.css' %}" rel="stylesheet"/>
    <link href="{% static 'StoreApp/css/styles.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'StoreApp/css/material-design-iconic-font.css' %}">
</head>


{% endblock %}

{% block content %}

<div class="container">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-md-9">
                <div class="ibox">
                    <div class="ibox-title">
                        <span class="pull-right">(<strong>{{import_sum_cart}}</strong>) items</span>
                        <h5>Items in your cart</h5>
                    </div>
                    <a href="{% url 'cart:Empty' %}" class="text-muted"><i
                            class="fa fa-trash"></i> Empty Cart</a>
                    {% if request.session.cart.items %}
                        {% for key, value in request.session.cart.items %}
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table shoping-cart-table">
                                <tbody>
                                <tr>
                                    <td width="90">
                                        <div align="top">
                                            <img class="card-img-top" src="{{value.image}}" style="top: 0px;">
                                        </div>
                                    </td>
                                    <td class="desc">
                                        <h3>
                                            <a href="" class="text-navy">
                                                {{value.name}}
                                            </a>
                                        </h3>
                                        <p class="small">
                                            {{value.description}}
                                        </p>
                                        <dl class="small m-b-none">
                                            <dt>Category</dt>
                                            <dd>{{value.category}}</dd>
                                        </dl>

                                        <div class="m-t-sm">
                                            <a href="{% url 'cart:Add' value.product_id %}" class="text-muted"><i
                                                    class="fa fa-gift"></i> Add one item </a>
                                            |
                                            <a href="{% url 'cart:Rest' value.product_id %}" class="text-muted"><i
                                                    class="fa fa-trash"></i> Remove one item</a>

                                            <a href="{% url 'cart:Delete' value.product_id %}" class="text-muted"><i
                                                    class="fa fa-trash"></i> Delete item</a>
                                        </div>
                                    </td>
                                    <td width="65">
                                        <input type="text" class="form-control" placeholder="{{value.quantity}}">
                                    </td>
                                    <td>
                                        <h4>
                                            {{value.price}} $
                                        </h4>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                            {% endfor %}

                        {% else %}
                        <tr>
                            <td colspan="3">
                                <div class="alert alert-danger text-center">
                                    Empty products.
                                </div>
                            </td>
                        </tr>
                        {% endif %}
                    </div>
                    <div class="ibox-content">
                        <!--- button
                        <button class="btn btn-primary pull-right" style="background: #0b5ed7;"><i
                                class="fa fa fa-shopping-cart"></i> Checkout
                        </button>
                         --->
                        <form action="{% url 'Store' %}">
                            <button class="btn btn-white" style="background: #0b5ed7; color:white;"><i
                                    class="fa fa-arrow-left"></i>
                                Continue shopping
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Cart Summary</h5>
                </div>
                <div class="ibox-content">
                    <span>
                        Total
                    </span>
                    <h2 class="font-bold">
                        {{import_total_cart}} $
                    </h2>

                    <hr>
                    <span class="text-muted small">
                        *For United States, France and Germany applicable sales tax will be applied
                    </span>
                    <div class="m-t-sm">
                        <div class="btn-group">
                            <a href="#" class="btn btn-primary btn-sm " style="background: #0b5ed7;"><i
                                    class="fa fa-shopping-cart"></i> Checkout</a>
                            <a href="#" class="btn btn-white btn-sm"> Cancel</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ibox">
                <div class="ibox-title">
                    <h5>Support</h5>
                </div>
                <div class="ibox-content text-center">
                    <h3><i class="fa fa-phone"></i> +43 100 783 001</h3>
                    <span class="small">
                        Please contact with us if you have any questions. We are avalible 24h.
                    </span>
                </div>
                <a href="{% url 'Contact' %}" class="btn btn-primary btn-sm " style="background: #0b5ed7;"><i
                        class="fa fa-shopping-cart"></i> Contact Us</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

StoreApp/templates/store/store.html
{% extends "OnlineStoreApp/base.html" %}

{% load static %}

{% block head %}

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Online Store</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'OnlineStoreApp/assets/base.ico' %}"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'OnlineStoreApp/css/styles.css' %}" rel="stylesheet"/>
    <link href="{% static 'StoreApp/css/styles.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'StoreApp/css/material-design-iconic-font.css' %}">
</head>


{% endblock %}

{% block header %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Store</h1>
            <p class="lead fw-normal text-white-50 mb-0"></p>
        </div>
        <div class="input-group">
            <form action="" method="GET" class="input-group">
                <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" name="search"
                       aria-describedby="search-addon" value="{{ request.GET.search}}"/>
                <button type="submit" class="btn btn-outline-primary">search</button>
            </form>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in products %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{product.image.url}}">
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{product.name}}</h5>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center">{{product.description}}</div>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        {% if product.price == 0%}
                        <div class="text-center"><strong>FREE</strong></div>
                        {% else %}
                        <div class="text-center"><strong>{{product.price}} $</strong></div>
                        {% endif %}
                    </div>
                    <div class="card-buttons" style="text-align: center;">
                        <div onclick="window.location.href='{% url 'cart:Add' product.id %}'" class="text-center"><a
                                class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                        <a class="btn btn--mini-rounded"></a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <!--Pagination-->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if products.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% endif %}
            {% for i in products.paginator.page_range %}
            {% if products.number == i %}
            <li class="page-item active" aria-current="page">
              <span class="page-link">
                {{ i }}
              </span>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <!--end of Pagination-->
</section>

{% endblock %}